site_name: Gomark.core

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Início: index.md
  - Campanhas: campanhas.md
  - FAQ: faq.md
  - Fornecedores: fornecedores.md
