site_name: Gomark.core

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - navigation.sections
    - navigation.expand
    - hide.footer

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Início: index.md
  - Campanhas:
      - Calendários: "Campanhas/Calendários.md"
      - Listar campanhas: "Campanhas/Listar campanhas.md"
      - Mídias rápidas: "Campanhas/Mídias rápidas.md"
      - Modelos de diagramação: "Campanhas/Modelos de diagramação.md"
      - Modelos de mídia: "Campanhas/Modelos de mídia.md"
      - Painel de controle: "Campanhas/Painel de controle.md"
      - Selos: "Campanhas/Selos.md"
  - Operacional:
      - Clusters: "Operacional/Clusters.md"
      - Cadastro de Fornecedores: "Operacional/Cadastro de Fornecedores.md"
      - Unidades: "Operacional/Unidades.md"
  - Cadastro de Produtos: "Cadastro de Produtos.md"
  - Portal do fornecedor: "Portal do fornecedor.md"


docs_dir: docs
