site_name: Gomark.core

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Início: index.md
  - Campanhas: Campanhas/Campanhas.md
  - FAQ: FAQ/FAQ.md
  - Fornecedores: Fornecedores/Fornecedores.md
